[versions]
skyhanni = "4.12.0"
libautoupdate = "1.3.1"
headlessLwjgl = "1.7.2"
jbAnnotations = "24.1.0"
meowdding-ktmodules = "1.0.3+java-8"

[libraries]
skyhanni = { module = "com.github.hannibal002:SkyHanni", version.ref = "skyhanni"}
headlessLwjgl = { module = "com.github.3arthqu4ke.HeadlessMc:headlessmc-lwjgl", version.ref = "headlessLwjgl" }
jbAnnotations = { module = "org.jetbrains:annotations", version.ref = "jbAnnotations" }
libautoupdate = { module = "moe.nea:libautoupdate", version.ref = "libautoupdate" }
meowdding-ktmodules = { module = "me.owdding.ktmodules:KtModules", version.ref = "meowdding-ktmodules" }
